config/routes.rb
Rails.application.routes.draw do
  
  root 'epicenter#feed'

  get 'all_users' => 'epicenter#all_users'
  get 'following' => 'epicenter#following'
  get 'followers' => 'epicenter#followers'

  get 'show_user' => 'epicenter#show_user'

  get 'now_following' => 'epicenter#now_following'

  get 'unfollow' => 'epicenter#unfollow'

  get 'tag_tweets' => 'epicenter#tag_tweets'

  resources :tweets
  devise_for :users

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord

	has_many :tweet_tags
	has_many :tweets, through: :tweet_tags

end

app/models/tweet.rb
class Tweet < ApplicationRecord

	before_validation :link_check, on: :create

	belongs_to :user

	has_many :tweet_tags
	has_many :tags, through: :tweet_tags
	

	validates :message, presence: true, length: {maximum: 140, too_long: "A tweet is only 140 characters. Everyone knows that!"}

	after_validation :apply_link, on: :create

	private 

	def apply_link
		array = self.message.split
		index = array.map { |x| x.include?("http://") || x.include?("https://") }.index(true)
		
		if index 
			url = array[index]
			array[index] = "<a href='#{self.link}' target='_blank'>#{url}</a>"
		end

		self.message = array.join(" ")
	end



	def link_check

		if self.message.include? "http://"
			check = true 
		elsif self.message.include? "https://"
			check = true
		else 
			check = false
		end

		if check == true
			array = self.message.split
			index = array.map{ |x| x.include? "http"}.index(true)
			self.link = array[index]
			if array[index].length > 23
				array[index] = "#{array[index][0..20]}..."
			end

			self.message = array.join(" ")
		end

	end

end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord

	belongs_to :tweet
	belongs_to :tag

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets, dependent: :destroy
  serialize :following, Array

  mount_uploader :avatar, AvatarUploader

  validates	:username, presence: true, uniqueness: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :bio, :location, :avatar, :following])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :bio, :location, :avatar, :following])
  end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  
  before_action :set_user, only: [:following, :followers]

  def all_users
    @users = User.order(username: :asc)
  end

  def following
    @users = []

    User.all.each do |user|
      if @user.following.include?(user.id)
        @users.push(user)
      end
    end
  end

  def followers
    @users = []

    User.all.each do |user|
      if user.following.include?(@user.id)
        @users.push(user)
      end
    end

  end


  def tag_tweets
    @tag = Tag.find(params[:id])
  end


  def feed
  	@following_tweets = []
    @tweet = Tweet.new

  	Tweet.all.each do |tweet|
  		if current_user.id == tweet.user_id || current_user.following.include?(tweet.user_id)
  			@following_tweets.push(tweet)
  		end
  	end
  end

  def show_user
    @user = User.find(params[:id])
  end

  def now_following
    current_user.following.push(params[:id].to_i)
    current_user.save

    redirect_to show_user_path(id: params[:id])
  end

  def unfollow
    current_user.following.delete(params[:id].to_i)
    current_user.save

    redirect_to show_user_path(id: params[:id])
  end

  private 

  def set_user
    @user = User.find(params[:id])
  end


end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  include TweetsHelper
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save

        get_tagged(@tweet)

        format.html { redirect_to root_url, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper

	def get_tagged(tweet)
		message_array = @tweet.message.split

        message_array.each_with_index do |word, index|
          if word[0] == "#"
            if Tag.pluck(:phrase).include?(word)
              tag = Tag.find_by(phrase: word)
            else
              tag = Tag.create(phrase: word)
            end
            tweet_tag = TweetTag.create(tweet_id: tweet.id, tag_id: tag.id)
            message_array[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"
          end
        end

        tweet.update(message: message_array.join(" "))
	end

end

app/views/epicenter/_user_list.html.erb
<div class="row">
	<% @users.each_with_index do |user, index| %>
		<div class="col-md-3">
			<div class="well user-list-wells">
				<div class="row">
					<div class="col-md-6">
						<% unless user.avatar.blank? %>
						<%= image_tag user.avatar.url, size: 100 %>
						<% end %>
					</div>
					<div class="col-md-6">
						<p>
							<% if current_user.following.include?(user.id) %>
								<%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-primary", id: "unfollow_btn_#{index}" %>
							<% else %>
								<% if current_user.id != user.id %>
									<%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary" %>
								<% end %>
							<% end %>
						</p>
					</div>
				</div>
				<div class="row">
					<%= link_to show_user_path(id: user.id) do %>
						<h3><%= user.name %></h3>
						<p><%= "@#{user.username}" %></p>
					<% end %>
					<p>
						<%= user.bio %>
					</p>
				</div>
			</div>
		</div>

	<script>
	   $(document).ready(function() {
		$('#unfollow_btn_<%= index %>').hover(function() {
			$(this).removeClass('btn-primary');
			$(this).addClass('btn-danger');
			$(this).html("Unfollow");
		}, function(){
			$(this).html("Following");
			$(this).removeClass("btn-danger");
			$(this).addClass("btn-primary");
		});
	   });
	</script>
 

<% end %>
</div>

app/views/epicenter/all_users.html.erb
<h1>All Twitter Users</h1>

<%= render 'user_list' %>

app/views/epicenter/feed.html.erb
<h1>@<%= current_user.username %>'s Twitter Feed</h1>

<%= render 'tweets/form', tweet: @tweet %>

<h3>Here is what your "friends" are saying:</h3>

<% @following_tweets.reverse_each do |tweet| %>
	<div class="well">
		<p>
			<%= image_tag tweet.user.avatar.url, size: 25 %>
			<%= tweet.user.name %>
			<%= link_to "@#{tweet.user.username}", show_user_path(id: tweet.user.id) %>
			• <%= time_ago_in_words(tweet.created_at) if Time.now - tweet.created_at < 86400 %>
			<%= tweet.created_at.strftime('%b %e') if Time.now - tweet.created_at> 86400 %>
		</p>
		<p><%= tweet.message.html_safe %></p>
	</div>
<% end %>

app/views/epicenter/followers.html.erb
<h1><%= @user.name %>'s followers:</h1>

<%= render 'user_list' %>

app/views/epicenter/following.html.erb
<h1><%= @user.name %> is following: </h1>

<%= render 'user_list' %>

app/views/epicenter/show_user.html.erb
<h1>@<%= @user.username %>'s Profile & Tweets</h1>

<h4><%= @user.name %></h4>
<h4><%= @user.location %></h4>
<h4><%= @user.bio %></h4>

<%= link_to "Followers", followers_path(id: @user.id), class: "btn btn-default" %> |
<%= link_to "Following", following_path(id: @user.id), class: "btn btn-default" %>

<p>
	<% if current_user.following.include?(@user.id) %>
		<%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-primary", id: "unfollow_btn" %>
	<% else %>
		<% if current_user.id != @user.id %>
			<%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>
		<% end %>
	<% end %>
</p>

<% @user.tweets.order(created_at: :desc).each do |tweet| %>

	<div class="well">
		<p>
			<%= image_tag tweet.user.avatar.url, size: 25 %>
			<%= tweet.user.name %>
			@<%= tweet.user.username %>
			• <%= time_ago_in_words(tweet.created_at) if Time.now - tweet.created_at < 86400 %>
			<%= tweet.created_at.strftime('%b %e') if Time.now - tweet.created_at> 86400 %>
		</p>
		<p><%= tweet.message.html_safe %></p>
	</div>

<% end %>

app/views/epicenter/tag_tweets.html.erb
<h1><%= @tag.phrase %></h1>

<% @tag.tweets.order(created_at: :desc).each do |tweet| %>

	<div class="well">
		<p>
			<%= image_tag tweet.user.avatar.url, size: 25 %>
			<%= tweet.user.name %>
			<%= link_to "@#{tweet.user.username}", show_user_path(id: tweet.user.id) %>
			• <%= time_ago_in_words(tweet.created_at) if Time.now - tweet.created_at < 86400 %>
			<%= tweet.created_at.strftime('%b %e') if Time.now - tweet.created_at> 86400 %>
		</p>
		<p><%= tweet.message.html_safe %></p>
	</div>

<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Home", root_path, class: "navbar-brand" %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Compose New Tweet", new_tweet_path %></li>
          <li><%= link_to "All Users", all_users_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Followers", followers_path(id: current_user.id) %></li>
            <li><%= link_to "Following", following_path(id: current_user.id) %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <% if current_user.avatar.blank? == false %>
                  <%= image_tag current_user.avatar.url, size:25 %>
                <% end %> 
                @<%= current_user.username %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
  	<div class="container">
    	<%= yield %>
	</div>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :message, id: :tweet_message, placeholder: "What's Happening?", class: "form-control" %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, id: :tweet_user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit "Tweet!", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table class="table">
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <td>Created At</td>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message %></td>
        <td><%= link_to tweet.user.username, show_user_path(id: tweet.user_id) %></td>
        <td><%= tweet.created_at %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<h3>@<%= @tweet.user.username %>'s Tweet</h3>

<div class="well">
	<p>
		<%= image_tag @tweet.user.avatar.url, size: 25 %>
		<%= @tweet.user.name %>
		@<%= @tweet.user.username %>
		• <%= time_ago_in_words(@tweet.created_at) %>
	</p>
	<p><%= @tweet.message.html_safe %></p>
</div>



<%= link_to 'Edit', edit_tweet_path(@tweet), class: "btn btn-warning" %> |
<%= link_to 'Back', tweets_path, class: "btn btn-default" %>